:imagesdir: images

= Exercise Four

=== Working with Dockerfiles

Once you understand how images and containers can be created from the command line, you can try building containers in a more permanent way. Building container images from Dockerfile files is by far the preferred way to create Docker formatted containers, as compared to modifying running containers and committing them to images.

The procedure here involves creating a Dockerfile file that includes many of the features illustrated earlier:

- Choosing a base image (i.e. Fedora)

- Installing the packages needed (i.e. an Postgresql Server)

- Mapping the server’s port (i.e. 5432)

- Launching the Database server

First get the Dockerfile from GitHub using curl.

.Get file
[source]
----
# curl -s -o Dockerfile https://raw.githubusercontent.com/jason-callaway/openstackdc/master/Dockerfile_fedora-postgres
----

.Dockerfile
[source]
----
# cat Dockerfile

FROM fedora
MAINTAINER jcallawa@redhat.com
RUN dnf install -y postgresql-server
USER postgres
RUN /bin/initdb -D /var/lib/pgsql/data
RUN /usr/bin/pg_ctl start -D /var/lib/pgsql/data -s -o "-p 5432" -w -t 300 &&\
    /bin/psql --command "CREATE USER docker WITH SUPERUSER PASSWORD 'docker';" &&\
    /bin/createdb -O docker docker
RUN echo "host all  all    0.0.0.0/0  md5" >> /var/lib/pgsql/data/pg_hba.conf
RUN echo "listen_addresses='*'" >> /var/lib/pgsql/data/postgresql.conf
EXPOSE 5432
VOLUME	["/var/lib/pgsql/data"]
CMD ["/bin/postgres", "-D", "/var/lib/pgsql/data", "-c", "config_file=/var/lib/pgsql/data/postgresql.conf"]
----

.Build

Please note that the docker build command on the second line below ends in a period (`.`).

[source]
----
# mkdir build; mv Dockerfile build/Dockerfile
# cd build; docker build -t fedora_postgresql .
----


.Run
[source]
----
# docker run -d --name fpg fedora_postgresql

2d89a041d4c9ba54628e1bbf6030e734b7b9e43d983a9d66828c96e185078b7c

# docker exec -ti fpg psql

psql (9.5.4)
Type "help" for help.

postgres=# \l

                             List of databases
   Name    |  Owner   | Encoding  | Collate | Ctype |   Access privileges   
-----------+----------+-----------+---------+-------+-----------------------
 docker    | docker   | SQL_ASCII | C       | C     | 
 postgres  | postgres | SQL_ASCII | C       | C     | 
 template0 | postgres | SQL_ASCII | C       | C     | =c/postgres          +
           |          |           |         |       | postgres=CTc/postgres
 template1 | postgres | SQL_ASCII | C       | C     | =c/postgres          +
           |          |           |         |       | postgres=CTc/postgres
(4 rows)

postgres=# \q
----




image::redhat.svg['Red Hat']
